title: Trust Check
author:
  name: TrustCheckCZ
  email: blog@trustcheck.cz

description: >
  A small blog about personal security and privacy, helping you safeguard your data and keep your online presence secure.

# theme: minima
remote_theme: "jeffreytse/jekyll-theme-yat"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap  # Include a sitemap for better SEO crawling

# SEO and Embed Improvements

defaults:
  - scope:
      path: ""
    values:
      og:title: "TrustCheck.CZ"
      og:description: "A blog to guide you on securing your personal privacy and data."
      og:image: "/assets/images/banner.png"  # Ensure you have this image for previews
      og:type: "website"
      og:url: "https://blog.trustcheck.cz/"
      twitter:card: "summary_large_image"
      twitter:title: "TrustCheck.CZ"
      twitter:description: "A blog to guide you on securing your personal privacy and data."
      twitter:image: "/assets/images/banner.png"  # Same image for Twitter cards

# If you have a favicon, link it here
favicon: "/assets/images/favicon.svg"

# Header navigation
header_pages:
  - about.md

# Excerpts
show_excerpts: true

# Minima Theme-specific settings
minima:
  skin: dark
  date_format: "%b %d, %Y"

  # Social Links in Footer
  social_links:
    - { platform: github, user_url: "https://github.com/TrustCheckCZ" }

# Sitemap for SEO
sitemap:
  exclude:
    - "/404.html"
    - "/offline.html"
  include_posts:
    - "/blog/"

# Add canonical URLs for better SEO
jekyll-seo-tag:
  og:
    title: "Privacy ToGo"
    description: "Your go-to guide for privacy and security in the digital world."
    url: "https://trustcheck.cz/privacytogo"
    image: "/assets/images/social-preview.png"
    site_name: "Privacy ToGo"
  twitter:
    card: "summary_large_image"

# Optional: Add some keywords for SEO
meta_keywords: "privacy, security, personal data, encryption, secure browsing, trustcheck, blog, trustcheck.cz, social security, online"

disqus:
  shortname: trustcheckcz
